# Generated by Django 4.2 on 2024-04-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20240425_1130'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                INSERT INTO `empat_weather`.`auth_user`
                (`id`,
                `password`,
                `last_login`,
                `is_superuser`,
                `username`,
                `first_name`,
                `last_name`,
                `email`,
                `is_staff`,
                `is_active`,
                `date_joined`)
                VALUES
                (9999,
                'pbkdf2_sha256$600000$JP9BmN8ESUAegYOHfehcvV$Gz7XC1CwDAP31RMRAjXsbJ9a7cV2pnAxEoJiltNshY0=',
                null,
                0,
                'demo_user1',
                '',
                '',
                'demo_user1@gmail.com',
                0,
                1,
                '2024-04-09 02:57:46.407869');

                INSERT INTO `empat_weather`.`weather_setting`
                (`id`,
                `city`,
                `unit`,
                `user_id`)
                VALUES
                (9999,
                'JAKARTA',
                'CELCIUS',
                9999);

            '''
        )
    ]
